/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pooproject;

import GestionDeConsultorios.Consultorio;
import GestionDeConsultorios.gestionConsultorio;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author santiago
 */
public class gestorConsultorioPanel extends javax.swing.JPanel {

    /**
     * Creates new form gestionConsultorioPanel
     */
    
    private gestionConsultorio gestor;
    
    public gestorConsultorioPanel() {
        initComponents();
        
        gestor = new gestionConsultorio(30);
        
        gestor.crearConsultorio(new Consultorio("C-01", "Oftamología", "Disponible"));
        gestor.crearConsultorio(new Consultorio("C-02", "Pediatría", "Ocupado"));
        gestor.crearConsultorio(new Consultorio("C-03", "Medicina General", "Mantenimiento"));
        
        cargarTablaConsultorios();
        
       

    }
    
    public void cargarTablaConsultorios() {
        String[] nombresColumnas = {"Código", "Especialidad", "Estado"};
        DefaultTableModel modelo = new DefaultTableModel(null, nombresColumnas);
        
        Consultorio[] lista = gestor.listar();
        
        for (int i = 0; i < gestor.cantidad(); i++) {
            Consultorio c = lista[i];
            Object[] fila = new Object[]{
                c.getCodigo(), 
                c.getEspecialidad(), 
                c.getEstado()
            };
            modelo.addRow(fila);
        }
        
        jtConsultorios.setModel(modelo); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtConsultorios = new javax.swing.JTable();
        bAgregar = new javax.swing.JButton();
        bEliminar = new javax.swing.JButton();
        bVer = new javax.swing.JButton();
        bModiciar = new javax.swing.JButton();

        jtConsultorios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtConsultorios);

        bAgregar.setText("Agregar");
        bAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAgregarActionPerformed(evt);
            }
        });

        bEliminar.setText("Eliminar");

        bVer.setText("Ver");

        bModiciar.setText("Modificar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bAgregar)
                        .addGap(10, 10, 10)
                        .addComponent(bModiciar)
                        .addGap(18, 18, 18)
                        .addComponent(bEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bVer))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAgregar)
                    .addComponent(bEliminar)
                    .addComponent(bVer)
                    .addComponent(bModiciar))
                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgregarActionPerformed
        // TODO add your handling code here:
        datosConsultorio formDatos = new datosConsultorio();
        formDatos.setVisible(true);
    }//GEN-LAST:event_bAgregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAgregar;
    private javax.swing.JButton bEliminar;
    private javax.swing.JButton bModiciar;
    private javax.swing.JButton bVer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtConsultorios;
    // End of variables declaration//GEN-END:variables
}
