/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pooproject;

import Model.Usuario;

/**
 *
 * @author santiago
 */
public class MenuDeOpciones extends javax.swing.JFrame {

    /**
     * Creates new form MenuDeOpciones
     */
    public MenuDeOpciones(Usuario user) {
        initComponents();
        
        switch (user.getRole()){
            case "Administrador":
                this.miConsultas.setEnabled(true);
                this.miReportes.setEnabled(true);
                this.miPacientes.setEnabled(true);
                this.miEmpleados.setEnabled(true);
                this.miConsultorios.setEnabled(true);
                break;
            case "Médico":
                this.miConsultas.setEnabled(true);
                this.miReportes.setEnabled(false);
                this.miPacientes.setEnabled(false);
                this.miEmpleados.setEnabled(false);
                this.miConsultorios.setEnabled(true);
                break;
            case "Enfermera":
                this.miConsultas.setEnabled(false);
                this.miReportes.setEnabled(false);
                this.miPacientes.setEnabled(true);
                this.miEmpleados.setEnabled(false);
                this.miConsultorios.setEnabled(true);
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miEmpleados = new javax.swing.JMenuItem();
        miConsultorios = new javax.swing.JMenuItem();
        miReportes = new javax.swing.JMenuItem();
        miConsultas = new javax.swing.JMenuItem();
        miPacientes = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenu1.setText("Menu");

        miEmpleados.setText("Empleados");
        miEmpleados.setEnabled(false);
        miEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEmpleadosActionPerformed(evt);
            }
        });
        jMenu1.add(miEmpleados);

        miConsultorios.setText("Consultorios");
        miConsultorios.setEnabled(false);
        jMenu1.add(miConsultorios);

        miReportes.setText("Reportes");
        miReportes.setEnabled(false);
        miReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miReportesActionPerformed(evt);
            }
        });
        jMenu1.add(miReportes);

        miConsultas.setText("Consultas");
        miConsultas.setEnabled(false);
        jMenu1.add(miConsultas);

        miPacientes.setText("Pacientes");
        miPacientes.setEnabled(false);
        jMenu1.add(miPacientes);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEmpleadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miEmpleadosActionPerformed

    private void miReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miReportesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miReportesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuDeOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuDeOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuDeOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuDeOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuDeOpciones(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem miConsultas;
    private javax.swing.JMenuItem miConsultorios;
    private javax.swing.JMenuItem miEmpleados;
    private javax.swing.JMenuItem miPacientes;
    private javax.swing.JMenuItem miReportes;
    // End of variables declaration//GEN-END:variables
}
