/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;
import GestionDeConsultorios.Cita;
import GestionDeConsultorios.Consultorio; // Importar Consultorio
import GestionDeFacturacion.Factura;
import javax.swing.JOptionPane;
/**
 *
 * @author santiago
 */
public class gestorReportePanel extends javax.swing.JPanel {

    /**
     * Creates new form gestorReportePanel
     */
    public gestorReportePanel() {
        initComponents();
        generarReportes();
    }
    
    public void generarReportes() {
        try {
            int totalPacientes = SistemaClinico.gestionPacientes.cantidad();
            jtTotalPacientes.setText(String.valueOf(totalPacientes));

            int atendidas = 0;
            Cita[] citas = SistemaClinico.gestionCitas.listar();
            for (int i = 0; i < SistemaClinico.gestionCitas.cantidad(); i++) {
                if ("Atendida".equals(citas[i].getEstado())) {
                    atendidas++;
                }
            }
            jtCitasAtendidas.setText(String.valueOf(atendidas));

            int ocupados = 0;
            Consultorio[] cons = SistemaClinico.gestionConsultorios.listar();
            for(int i=0; i < SistemaClinico.gestionConsultorios.cantidad(); i++){
                if("Ocupado".equalsIgnoreCase(cons[i].getEstado())){ 
                    ocupados++;
                }
            }
            jtConsultoriosOcupados.setText(String.valueOf(ocupados));

            double totalDinero = 0.0;
            Factura[] facturas = SistemaClinico.gestionFacturas.listar();
            for (int i = 0; i < SistemaClinico.gestionFacturas.cantidad(); i++) {
                totalDinero += facturas[i].getMonto();
            }
            jtIngresosTotales.setText("S/. " + totalDinero);
            
        } catch (Exception e) {
            jtIngresosTotales.setText("Error al calcular");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtTotalPacientes = new javax.swing.JTextField();
        jtCitasAtendidas = new javax.swing.JTextField();
        jtConsultoriosOcupados = new javax.swing.JTextField();
        jtIngresosTotales = new javax.swing.JTextField();
        bActualizar = new javax.swing.JButton();

        jLabel1.setText("REPORTES");

        jLabel2.setText("Total de Pacientes Registrados");

        jLabel3.setText("Total de Citas Atendidas");

        jLabel4.setText("Total de Consultorios Ocupados");

        jLabel5.setText("Ingresos Totales (S/)");

        jtTotalPacientes.setEnabled(false);

        jtCitasAtendidas.setEnabled(false);

        jtConsultoriosOcupados.setEnabled(false);

        jtIngresosTotales.setEnabled(false);

        bActualizar.setText("Actualizar Reporte");
        bActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bActualizar)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtTotalPacientes, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                            .addComponent(jtCitasAtendidas)
                            .addComponent(jtConsultoriosOcupados)
                            .addComponent(jtIngresosTotales))))
                .addContainerGap(568, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtTotalPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtCitasAtendidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtConsultoriosOcupados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtIngresosTotales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bActualizar)
                .addContainerGap(193, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActualizarActionPerformed
        // TODO add your handling code here:
        generarReportes();
        JOptionPane.showMessageDialog(this, "Reportes ya actualizados.");
    }//GEN-LAST:event_bActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bActualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jtCitasAtendidas;
    private javax.swing.JTextField jtConsultoriosOcupados;
    private javax.swing.JTextField jtIngresosTotales;
    private javax.swing.JTextField jtTotalPacientes;
    // End of variables declaration//GEN-END:variables
}
