/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import GestionConsultas.Consultas;
import GestionDeFacturacion.Factura;
import GestionDePacientes.Paciente;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
/**
 *
 * @author santiago
 */
public class gestorFacturaPanel extends javax.swing.JPanel {
    private DefaultTableModel modeloFact;
    private double precioConsultaSeleccionada = 0.0;

    /**
     * Creates new form gestionFacturaPanel
     */
    public gestorFacturaPanel() {
        initComponents();
        
        modeloFact = new DefaultTableModel();
        
        modeloFact.addColumn("Nro Factura");
        modeloFact.addColumn("Descripción");
        modeloFact.addColumn("Monto Total");
        
        this.jtFacturas.setModel(modeloFact);
        
        cargarCombos(); 
        cargarTablaFacturas();
        limpiarCampos();
        
        jcbConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                if(jcbConsultas.getSelectedIndex() > 0) {
                    String paciente = (String) jcbConsultas.getSelectedItem();
                    jtDescripcion.setText("Atención a: " + paciente.split(" - ")[1]); 
                }
            }
        });
    }
    
    public void cargarCombos() {
        jcbConsultas.removeAllItems();
        jcbConsultas.addItem("-- Seleccione Consulta --");
        
        Consultas[] lista = SistemaClinico.gestionConsulta.listar();
        for(int i=0; i < SistemaClinico.gestionConsulta.cantidad(); i++){
            jcbConsultas.addItem(i + " - " + lista[i].getCita().getPaciente().getDni() + " - " + lista[i].getCita().getPaciente().getNombre() + " - " + lista[i].getCita().getPaciente().getApellido() + " - " + lista[i].getMotivo());
        }
    }

    public void cargarTablaFacturas() {
        int filas = this.jtFacturas.getRowCount();
        for (int i = 0; i < filas; i++) {
            modeloFact.removeRow(0);
        }

        Factura[] lista = SistemaClinico.gestionFacturas.listar();
        String[] datos = new String[3];
        
        for (int i = 0; i < SistemaClinico.gestionFacturas.cantidad(); i++) {
            datos[0] = String.valueOf(lista[i].getNumero());
            datos[1] = lista[i].getDescripcion();
            datos[2] = "S/. " + lista[i].getMonto(); 
            modeloFact.addRow(datos);
        }
    }

    public void configurarCampos(boolean habilitar) {
        jtNumero.setEnabled(habilitar);
        jtMonto.setEnabled(!habilitar);
        jtDescripcion.setEnabled(habilitar);
        jcbConsultas.setEnabled(habilitar);
    }

    public void limpiarCampos() {
        jtNumero.setText("");
        jtMonto.setText("");
        jtDescripcion.setText("");
        if(jcbConsultas.getItemCount() > 0) jcbConsultas.setSelectedIndex(0);
        precioConsultaSeleccionada = 0.0;
        
        configurarCampos(true);
        bVer.setText("Ver");
        bModificar.setText("Modificar");
        bAgregar.setEnabled(true);
        bEliminar.setEnabled(true);
        bVer.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtNumero = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtMonto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtDescripcion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jcbConsultas = new javax.swing.JComboBox<>();
        bAgregar = new javax.swing.JButton();
        bModificar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtFacturas = new javax.swing.JTable();
        bVer = new javax.swing.JButton();
        bEliminar = new javax.swing.JButton();
        jtEliminarNumero = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        jLabel1.setText("Datos Facturas");

        jLabel2.setText("Numero");

        jLabel3.setText("Monto");

        jtMonto.setEnabled(false);

        jLabel4.setText("Descripcion");

        jLabel5.setText("Consultas");

        jcbConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbConsultasActionPerformed(evt);
            }
        });

        bAgregar.setText("Agregar");
        bAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAgregarActionPerformed(evt);
            }
        });

        bModificar.setText("Modificar");
        bModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificarActionPerformed(evt);
            }
        });

        jtFacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jtFacturas);

        bVer.setText("Ver");
        bVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVerActionPerformed(evt);
            }
        });

        bEliminar.setText("Eliminar");
        bEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarActionPerformed(evt);
            }
        });

        jLabel6.setText("S/");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6))
                            .addComponent(jtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bAgregar)
                        .addGap(28, 28, 28)
                        .addComponent(bModificar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(bVer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtEliminarNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bEliminar)))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jcbConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(27, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bAgregar)
                        .addComponent(bModificar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bVer)
                        .addComponent(bEliminar)
                        .addComponent(jtEliminarNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgregarActionPerformed
        // TODO add your handling code here:
        try {
            if (jtNumero.getText().isEmpty() || jtMonto.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Complete el número y el monto.");
                return;
            }

            int numero = Integer.parseInt(jtNumero.getText());
            String desc = jtDescripcion.getText();
            double montoManual = 0.0;
            if (!jtMonto.getText().isEmpty()) {
                montoManual = Double.parseDouble(jtMonto.getText());
            }
            
            double montoTotal = precioConsultaSeleccionada + montoManual;

            if(SistemaClinico.gestionFacturas.buscarFactura(numero) != null){
                JOptionPane.showMessageDialog(this, "Ya existe una factura con ese número.");
                return;
            }

            Factura nuevaFactura = new Factura(numero, desc, montoTotal);
            
            String mensaje = SistemaClinico.gestionFacturas.crearFactura(nuevaFactura);
            JOptionPane.showMessageDialog(this, mensaje);

            if (!mensaje.startsWith("ERROR")) {
                cargarTablaFacturas();
                limpiarCampos();
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error: El Número debe ser entero y el Monto numérico.");
        }
    }//GEN-LAST:event_bAgregarActionPerformed

    private void bVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVerActionPerformed
        // TODO add your handling code here:
        if (bVer.getText().equals("Ver")) {
            int fila = jtFacturas.getSelectedRow();
            if (fila == -1) {
                javax.swing.JOptionPane.showMessageDialog(this, "Seleccione una factura.");
                return;
            }

            int numero = Integer.parseInt(jtFacturas.getValueAt(fila, 0).toString());
            Factura f = SistemaClinico.gestionFacturas.buscarFactura(numero);

            if (f != null) {
                jtNumero.setText(String.valueOf(f.getNumero()));
                jtDescripcion.setText(f.getDescripcion());
                jtMonto.setText(String.valueOf(f.getMonto()));
                
                configurarCampos(false);
                
                bVer.setText("Dejar de ver");
                bAgregar.setEnabled(false);
                bEliminar.setEnabled(false);
                bModificar.setEnabled(false);
            }
        } else {
            limpiarCampos();
        }
    }//GEN-LAST:event_bVerActionPerformed

    private void bModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificarActionPerformed
        // TODO add your handling code here:
        if (bModificar.getText().equals("Modificar")) {
            int fila = jtFacturas.getSelectedRow();
            if (fila == -1) {
                JOptionPane.showMessageDialog(this, "Seleccione una factura para editar.");
                return;
            }

            bVerActionPerformed(evt);

            configurarCampos(true);
            jtNumero.setEnabled(false);
            
            bModificar.setText("Guardar Cambios");
            bAgregar.setEnabled(false);
            bEliminar.setEnabled(false);
            bVer.setEnabled(false);
            
        } else {
            try {
                int numero = Integer.parseInt(jtNumero.getText());
                double nuevoMonto = Double.parseDouble(jtMonto.getText());
                String nuevaDesc = jtDescripcion.getText();
                
                String mensaje = SistemaClinico.gestionFacturas.modificarFactura(numero, nuevaDesc, nuevoMonto);
                JOptionPane.showMessageDialog(this, mensaje);
                
                if (!mensaje.startsWith("ERROR")) {
                    cargarTablaFacturas();
                    limpiarCampos();
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Error en el formato del monto.");
            }
        }
    }//GEN-LAST:event_bModificarActionPerformed

    private void bEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarActionPerformed
        // TODO add your handling code here:
        try {
            String textoEliminar = jtEliminarNumero.getText();
            if(textoEliminar.isEmpty()){
                JOptionPane.showMessageDialog(this, "Escriba el N° de Factura a eliminar.");
                return;
            }
            
            int numero = Integer.parseInt(textoEliminar);
            
            int confirm = JOptionPane.showConfirmDialog(this, "¿Anular factura N° " + numero + "?");
            if (confirm == JOptionPane.YES_OPTION) {
                String mensaje = SistemaClinico.gestionFacturas.eliminarFactura(numero);
                JOptionPane.showMessageDialog(this, mensaje);
                
                if (!mensaje.startsWith("ERROR")) {
                    cargarTablaFacturas();
                    jtEliminarNumero.setText("");
                    limpiarCampos();
                }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El número de factura debe ser un entero.");
        }
    }//GEN-LAST:event_bEliminarActionPerformed

    private void jcbConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbConsultasActionPerformed
        // TODO add your handling code here:
        if (jcbConsultas.getSelectedIndex() > 0) {
            try {
                String seleccion = (String) jcbConsultas.getSelectedItem();
                int index = Integer.parseInt(seleccion.split(" - ")[0]);
                GestionConsultas.Consultas consulta = SistemaClinico.listarConsultas()[index];
                precioConsultaSeleccionada = consulta.getPrecio();
                jtMonto.setText(String.valueOf(precioConsultaSeleccionada));
                
  
            } catch (Exception e) {
                precioConsultaSeleccionada = 0.0;
            }
        } else {
            precioConsultaSeleccionada = 0.0;
            jtDescripcion.setText("");
        }
    }//GEN-LAST:event_jcbConsultasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAgregar;
    private javax.swing.JButton bEliminar;
    private javax.swing.JButton bModificar;
    private javax.swing.JButton bVer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jcbConsultas;
    private javax.swing.JTextField jtDescripcion;
    private javax.swing.JTextField jtEliminarNumero;
    private javax.swing.JTable jtFacturas;
    private javax.swing.JTextField jtMonto;
    private javax.swing.JTextField jtNumero;
    // End of variables declaration//GEN-END:variables
}
