/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import GestionDeConsultorios.Consultorio;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author santiago
 */
public class gestorConsultorioPanel extends javax.swing.JPanel {

    /**
     * Creates new form gestionConsultorioPanel
     */
    
    private DefaultTableModel modelo;
    
    public gestorConsultorioPanel() {
        initComponents();
        modelo = new DefaultTableModel();
        modelo.addColumn("Codigo");
        modelo.addColumn("Especialidad");
        modelo.addColumn("Estado");
        this.jtConsultorios.setModel(modelo);
        
        configurarCampos(true);
        
        cargarTablaConsultorios();
    }
    
    public void cargarTablaConsultorios() {

        int filas = this.jtConsultorios.getRowCount();
        for (int i = 0; i < filas; i++) {
            modelo.removeRow(0);
        }
        
        Consultorio[] arreglo = SistemaClinico.gestionConsultorios.listar();
        String[] datos = new String[3];
        for (int i =0; i< SistemaClinico.gestionConsultorios.cantidad(); i++){
            datos[0]= String.valueOf(arreglo[i].getCodigo());
            datos[1]= arreglo[i].getEspecialidad();
            datos[2] = arreglo[i].getEstado();
            modelo.addRow(datos);
        }
        
    
    }
    
    public void configurarCampos(boolean habilitar) {
        jtCodigo.setEnabled(habilitar);
        jcbEspecialidad.setEnabled(habilitar);
        jcbEstado.setEnabled(habilitar);

        jCheckBox1.setEnabled(habilitar);
        jCheckBox2.setEnabled(habilitar);
        jCheckBox3.setEnabled(habilitar);
        jCheckBox4.setEnabled(habilitar);
        jCheckBox6.setEnabled(habilitar);
        jCheckBox7.setEnabled(habilitar);
        jCheckBox8.setEnabled(habilitar);
        
    }
    
    public void cargarDatosDetalle(Consultorio c) {

        jtCodigo.setText(String.valueOf(c.getCodigo()));
        jcbEspecialidad.setSelectedItem(c.getEspecialidad());
        jcbEstado.setSelectedItem(c.getEstado());

        boolean[] horario = c.getHorarioDisponible();
        jCheckBox1.setSelected(horario[0]); 
        jCheckBox2.setSelected(horario[1]);
        jCheckBox3.setSelected(horario[2]);
        jCheckBox4.setSelected(horario[3]);
        jCheckBox6.setSelected(horario[4]);
        jCheckBox7.setSelected(horario[5]);
        jCheckBox8.setSelected(horario[6]);
    }
    
    public void limpiarCampos() {
        jtCodigo.setText("");
        jcbEspecialidad.setSelectedIndex(0);
        jcbEstado.setSelectedIndex(0);

        jCheckBox1.setSelected(false); jCheckBox2.setSelected(false);
        jCheckBox3.setSelected(false); jCheckBox4.setSelected(false);
        jCheckBox6.setSelected(false); jCheckBox7.setSelected(false);
        jCheckBox8.setSelected(false);

        configurarCampos(true);
        bModiciar.setText("Modificar");
        bAgregar.setEnabled(true);
        bEliminar.setEnabled(true);
        bVer.setEnabled(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtConsultorios = new javax.swing.JTable();
        bAgregar = new javax.swing.JButton();
        bEliminar = new javax.swing.JButton();
        bVer = new javax.swing.JButton();
        bModiciar = new javax.swing.JButton();
        jtCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jcbEspecialidad = new javax.swing.JComboBox<>();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jCheckBox3 = new javax.swing.JCheckBox();
        jcbEstado = new javax.swing.JComboBox<>();
        jCheckBox4 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtEliminarCod = new javax.swing.JTextField();

        jtConsultorios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtConsultorios);

        bAgregar.setText("Agregar");
        bAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAgregarActionPerformed(evt);
            }
        });

        bEliminar.setText("Eliminar");
        bEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarActionPerformed(evt);
            }
        });

        bVer.setText("Ver");
        bVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVerActionPerformed(evt);
            }
        });

        bModiciar.setText("Modificar");
        bModiciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModiciarActionPerformed(evt);
            }
        });

        jtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCodigoActionPerformed(evt);
            }
        });

        jLabel3.setText("Especialidad");

        jCheckBox1.setText("de 10am a 11am");

        jcbEspecialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Medicina General", "Pediatría", "Oftamología", "Cardiología", "Traumatología", "Psicología" }));
        jcbEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbEspecialidadActionPerformed(evt);
            }
        });

        jCheckBox2.setText("de 11am a 12pm");

        jLabel4.setText("Estado");

        jCheckBox3.setText("de 12pm a 1pm");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        jcbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disponible", "Ocupado", "Mantenimiento" }));

        jCheckBox4.setText("de 1pm a 2pm");

        jLabel5.setText("Horarios:");

        jCheckBox6.setText("de 2pm a 3pm");

        jCheckBox7.setText("de 3pm a 4pm");

        jCheckBox8.setText("de 4pm a 5pm");
        jCheckBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox8ActionPerformed(evt);
            }
        });

        jLabel1.setText("Datos Consultorio");

        jLabel2.setText("Codigo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbEspecialidad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox8)
                            .addComponent(jCheckBox7)
                            .addComponent(jCheckBox6)
                            .addComponent(jCheckBox2)
                            .addComponent(jCheckBox4)
                            .addComponent(jCheckBox3)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jCheckBox1))))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bModiciar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bVer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtEliminarCod, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bEliminar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jcbEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jcbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)))
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox2)
                                .addGap(9, 9, 9)
                                .addComponent(jCheckBox3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox4)
                                .addGap(5, 5, 5)
                                .addComponent(jCheckBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox8)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bEliminar)
                    .addComponent(bVer)
                    .addComponent(bModiciar)
                    .addComponent(bAgregar)
                    .addComponent(jtEliminarCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgregarActionPerformed
        // TODO add your handling code here: 
        try {
            if(this.jtCodigo.getText().isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Ingresa un codigo porque está vacío.");
            }
            int cod = Integer.parseInt(this.jtCodigo.getText());
            String esp = (String) this.jcbEspecialidad.getSelectedItem();
            String est = (String) this.jcbEstado.getSelectedItem();

            boolean[] horario = new boolean[7];

            horario[0] = jCheckBox1.isSelected();
            horario[1] = jCheckBox2.isSelected();
            horario[2] = jCheckBox3.isSelected();
            horario[3] = jCheckBox4.isSelected();
            horario[4] = jCheckBox6.isSelected();
            horario[5] = jCheckBox7.isSelected();
            horario[6] = jCheckBox8.isSelected();

            Consultorio ref = new Consultorio(cod, esp, est);

            ref.setHorarioDisponible(horario);
            
            String mensaje = SistemaClinico.gestionConsultorios.crearConsultorio(ref);

            javax.swing.JOptionPane.showMessageDialog(this, mensaje);

            if (!mensaje.startsWith("ERROR")) {
                cargarTablaConsultorios();
                limpiarCampos(); 
            }
            
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "El código debe ser un número entero.");
        }
      

        
    }//GEN-LAST:event_bAgregarActionPerformed

    private void jtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtCodigoActionPerformed

    private void jcbEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbEspecialidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbEspecialidadActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox8ActionPerformed

    private void bVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVerActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada =jtConsultorios.getSelectedRow();
        if (filaSeleccionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un consultorio de la tabla para ver horarios.");
            return;
        }
        
        try {
            Object valorTabla = jtConsultorios.getValueAt(filaSeleccionada, 0);
            String codigoStr = valorTabla.toString();

            int codigoConsultorio = Integer.parseInt(codigoStr);
            Consultorio consultorio = SistemaClinico.gestionConsultorios.buscar(codigoConsultorio);

            if(consultorio != null){
                cargarDatosDetalle(consultorio);
                configurarCampos(false);
                this.revalidate();
                this.repaint();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "No se pudo encontrar el consultorio.");
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Inserta un numero entero.");
        }
        
    }//GEN-LAST:event_bVerActionPerformed

    private void bModiciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModiciarActionPerformed
        // TODO add your handling code here:
        if (bModiciar.getText().equals("Modificar")) {

            int filaSeleccionada = jtConsultorios.getSelectedRow();
            if (filaSeleccionada == -1) {
                javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un consultorio de la tabla para modificar.");
                return;
            }

            try {
                Object valorTabla = jtConsultorios.getValueAt(filaSeleccionada, 0);
                int codigoConsultorio = Integer.parseInt(valorTabla.toString());

                Consultorio c = SistemaClinico.gestionConsultorios.buscar(codigoConsultorio);

                if (c != null) {
                    cargarDatosDetalle(c);

                    jtCodigo.setEnabled(false); 

                    jcbEspecialidad.setEnabled(true);
                    jcbEstado.setEnabled(true);

                    jCheckBox1.setEnabled(true); 
                    jCheckBox2.setEnabled(true);
                    jCheckBox3.setEnabled(true); 
                    jCheckBox4.setEnabled(true);
                    jCheckBox6.setEnabled(true); 
                    jCheckBox7.setEnabled(true);
                    jCheckBox8.setEnabled(true);

                    bModiciar.setText("Guardar Cambios");
                    bAgregar.setEnabled(false); 
                    bEliminar.setEnabled(false);
                    bVer.setEnabled(false);
                }
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error al cargar los datos para modificar.");
            }
        } else {
            try {
                int cod = Integer.parseInt(jtCodigo.getText());
                String nuevaEspecialidad = (String) jcbEspecialidad.getSelectedItem();
                String nuevoEstado = (String) jcbEstado.getSelectedItem();

                String mensaje = SistemaClinico.gestionConsultorios.modificarConsultorio(cod, nuevaEspecialidad, nuevoEstado);

                Consultorio c = SistemaClinico.gestionConsultorios.buscar(cod);
                if (c != null) {
                    boolean[] nuevoHorario = new boolean[7];
                    nuevoHorario[0] = jCheckBox1.isSelected();
                    nuevoHorario[1] = jCheckBox2.isSelected();
                    nuevoHorario[2] = jCheckBox3.isSelected();
                    nuevoHorario[3] = jCheckBox4.isSelected();
                    nuevoHorario[4] = jCheckBox6.isSelected();
                    nuevoHorario[5] = jCheckBox7.isSelected();
                    nuevoHorario[6] = jCheckBox8.isSelected();

                    c.setHorarioDisponible(nuevoHorario);
                }

                javax.swing.JOptionPane.showMessageDialog(this, mensaje);

                if (!mensaje.startsWith("ERROR")) {
                    cargarTablaConsultorios();
                    limpiarCampos();
                }

            } catch (NumberFormatException e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error en los datos numéricos.");
            }
        }
    }//GEN-LAST:event_bModiciarActionPerformed

    private void bEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarActionPerformed

        try {
            String codigoTexto = jtEliminarCod.getText();

            if(codigoTexto.isEmpty()) {
                 javax.swing.JOptionPane.showMessageDialog(this, "Ingrese el código del consultorio a eliminar en el recuadro.");
                 return;
            }

            int cod = Integer.parseInt(codigoTexto);

            int confirm = javax.swing.JOptionPane.showConfirmDialog(this, 
                    "¿Está seguro de eliminar el consultorio " + cod + "?",
                    "Confirmar Eliminación", javax.swing.JOptionPane.YES_NO_OPTION);

            if (confirm == javax.swing.JOptionPane.YES_OPTION) {
                String mensaje = SistemaClinico.gestionConsultorios.eliminarConsultorio(cod);

                javax.swing.JOptionPane.showMessageDialog(this, mensaje);

                if (!mensaje.startsWith("ERROR")) {
                    cargarTablaConsultorios();
                    jtEliminarCod.setText("");
                    limpiarCampos();
                }
            }

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "El código debe ser un número entero.");
        }
    }//GEN-LAST:event_bEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAgregar;
    private javax.swing.JButton bEliminar;
    private javax.swing.JButton bModiciar;
    private javax.swing.JButton bVer;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbEspecialidad;
    private javax.swing.JComboBox<String> jcbEstado;
    private javax.swing.JTextField jtCodigo;
    private javax.swing.JTable jtConsultorios;
    private javax.swing.JTextField jtEliminarCod;
    // End of variables declaration//GEN-END:variables
}
