/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import GestionDeEmpleados.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import Vista.SistemaClinico;

/**
 *
 * @author santiago
 */
public class gestorEmpleadoPanel extends javax.swing.JPanel {

    /**
     * Creates new form ges
     */
    private DefaultTableModel modeloEmpl;
    
    public gestorEmpleadoPanel() {
        initComponents();
        modeloEmpl = new DefaultTableModel();
        modeloEmpl.addColumn("DNI");
        modeloEmpl.addColumn("Nombres");
        modeloEmpl.addColumn("Apellidos");
        modeloEmpl.addColumn("Telefono");
        modeloEmpl.addColumn("E-mail");
        modeloEmpl.addColumn("Usuario");
        modeloEmpl.addColumn("Rol");
        this.jtEmpleados.setModel(modeloEmpl);
        
        cargarTablaEmpleados();
        
    }
    
    public void limpiarCampos() {
        jtDNI.setText("");
        jtNombres.setText("");
        jtApellidos.setText("");
        jtTelefono.setText("");
        jtEmail.setText("");
        jtUsuario.setText("");
        jtPassword.setText("");
        jcbRol.setSelectedIndex(0);
        jcbEspecialidad.setSelectedIndex(0);
        
        configurarCampos(true); 
        jcbEspecialidad.setEnabled(false); 
    }
    
    public void cargarTablaEmpleados() {
        int filas = this.jtEmpleados.getRowCount();
        for (int i = 0; i < filas; i++) {
            modeloEmpl.removeRow(0);
        }
        
        Empleado[] arreglo = SistemaClinico.gestionEmpleados.listar();
        String[] datos = new String[7];
        for (int i = 0; i < SistemaClinico.gestionEmpleados.cantidad(); i++) {
            datos[0] = String.valueOf(arreglo[i].getDni());
            datos[1] = arreglo[i].getNombre();
            datos[2] = arreglo[i].getApellido();
            datos[3] = arreglo[i].getTelefono();
            datos[4] = arreglo[i].getEmail();
            datos[5] = arreglo[i].getUsuario();
            datos[6] = arreglo[i].getRol();
            
            modeloEmpl.addRow(datos);
        }
    }
    
    public void configurarCampos(boolean habilitar) {
       jtDNI.setEnabled(habilitar); 
       jtNombres.setEnabled(habilitar);
       jtApellidos.setEnabled(habilitar);
       jtTelefono.setEnabled(habilitar);
       jtEmail.setEnabled(habilitar);
       jtUsuario.setEnabled(habilitar);
       jtPassword.setEnabled(habilitar);
       jcbRol.setEnabled(habilitar);

       if (!habilitar) {
           jcbEspecialidad.setEnabled(false);
       }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtConsultorios = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtEmpleados = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jlDNI = new javax.swing.JLabel();
        jtDNI = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtNombres = new javax.swing.JTextField();
        jtApellidos = new javax.swing.JTextField();
        jcbRol = new javax.swing.JComboBox<>();
        jtUsuario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtTelefono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtPassword = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jcbEspecialidad = new javax.swing.JComboBox<>();
        bAgregar = new javax.swing.JButton();
        bVer = new javax.swing.JButton();
        bModificar = new javax.swing.JButton();
        bEliminar = new javax.swing.JButton();
        jtEliminarDNI = new javax.swing.JTextField();

        jtConsultorios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtConsultorios);

        jtEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jtEmpleados);

        jLabel1.setText("Datos Empleado");

        jlDNI.setText("DNI");

        jtDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtDNIActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombres");

        jLabel3.setText("Apellidos");

        jLabel4.setText("Rol");

        jLabel5.setText("Usuario");

        jcbRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Cajero", "Médico", "Recepcionista", "Enfermero" }));
        jcbRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbRolActionPerformed(evt);
            }
        });

        jLabel6.setText("Telefono");

        jLabel7.setText("E-Mail");

        jLabel8.setText("Clave");

        jLabel9.setText("Especialidad");

        jcbEspecialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sin Especialidad", "Medicina General", "Pediatría", "Oftamología", "Cardiología", "Traumatología", "Psicología" }));
        jcbEspecialidad.setEnabled(false);

        bAgregar.setText("Agregar");
        bAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAgregarActionPerformed(evt);
            }
        });

        bVer.setText("Ver");
        bVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVerActionPerformed(evt);
            }
        });

        bModificar.setText("Modificar");
        bModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificarActionPerformed(evt);
            }
        });

        bEliminar.setText("Eliminar");
        bEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlDNI)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5))
                                .addGap(42, 42, 42))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(bAgregar)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtNombres)
                                    .addComponent(jtApellidos)
                                    .addComponent(jtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtEmail)
                                    .addComponent(jtUsuario)
                                    .addComponent(jtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel9)
                                    .addComponent(jcbRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcbEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(bModificar))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bVer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtEliminarDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bEliminar))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlDNI)
                            .addComponent(jtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(40, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAgregar)
                    .addComponent(bVer)
                    .addComponent(bModificar)
                    .addComponent(bEliminar)
                    .addComponent(jtEliminarDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtDNIActionPerformed

    private void bAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgregarActionPerformed
        // TODO add your handling code here:
        String dni = jtDNI.getText();
        String nombre = jtNombres.getText();
        String apellido = jtApellidos.getText();
        String telefono = jtTelefono.getText();
        String email = jtEmail.getText();
        String usuario = jtUsuario.getText();
        String password = jtPassword.getText();
        String rol = (String) jcbRol.getSelectedItem();

        Empleado nuevoEmpleado = null;

        switch (rol) {
            case "Médico":
            if (jcbEspecialidad.getSelectedIndex() == 0) {
                    JOptionPane.showMessageDialog(this, "Debe seleccionar una especialidad válida para el Médico.");
                    return; 
                }
                String especialidad = (String) jcbEspecialidad.getSelectedItem();
                nuevoEmpleado = new Medico(especialidad, dni, nombre, apellido, telefono, email, usuario, password, rol);
                break;
            case "Enfermero(a)":
            case "Enfermera":
            case "Enfermero":
            nuevoEmpleado = new Enfermero(dni, nombre, apellido, telefono, email, usuario, password, rol);
            break;
            case "Cajero":
            nuevoEmpleado = new Cajero(dni, nombre, apellido, telefono, email, usuario, password, rol);
            break;
            case "Administrador":
            nuevoEmpleado = new Administrador(dni, nombre, apellido, telefono, email, usuario, password, rol);
            break;
            case "Recepcionista":
            nuevoEmpleado = new Recepcionista(dni, nombre, apellido, telefono, email, usuario, password, rol);
            break;
            default:
            javax.swing.JOptionPane.showMessageDialog(this, "Elige un rol");
        }

        String mensaje = SistemaClinico.gestionEmpleados.crearEmpleado(nuevoEmpleado);

        JOptionPane.showMessageDialog(this, mensaje);
        if (!mensaje.startsWith("ERROR")) {
            cargarTablaEmpleados();
            limpiarCampos();
        }
    }//GEN-LAST:event_bAgregarActionPerformed

    private void jcbRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbRolActionPerformed
        // TODO add your handling code here:
        String rolSeleccionado = (String) jcbRol.getSelectedItem();

        if ("Médico".equals(rolSeleccionado)) {
            jcbEspecialidad.setEnabled(true);
        } else {
            jcbEspecialidad.setEnabled(false);
            jcbEspecialidad.setSelectedIndex(0); 
        }
    }//GEN-LAST:event_jcbRolActionPerformed

    private void bVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVerActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = jtEmpleados.getSelectedRow();
        if(filaSeleccionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un empleado.");
            return;
        }
        
        String dni = jtEmpleados.getValueAt(filaSeleccionada, 0).toString();
        
        Empleado empleadoEncontrado = SistemaClinico.gestionEmpleados.buscarPorDni(dni);
        
        if(empleadoEncontrado != null) {
            jtDNI.setText(empleadoEncontrado.getDni());
            jtNombres.setText(empleadoEncontrado.getNombre());
            jtApellidos.setText(empleadoEncontrado.getApellido());
            jtTelefono.setText(empleadoEncontrado.getTelefono());
            jtEmail.setText(empleadoEncontrado.getEmail());
            jtUsuario.setText(empleadoEncontrado.getUsuario());
            jtPassword.setText(empleadoEncontrado.getPassword());
            
            jcbRol.setSelectedItem(empleadoEncontrado.getRol());
            
            if (empleadoEncontrado instanceof Medico) {
                Medico medico = (Medico) empleadoEncontrado;
                jcbEspecialidad.setEnabled(true);
                jcbEspecialidad.setSelectedItem(medico.getEspecialidad());
            } else {
                jcbEspecialidad.setSelectedIndex(0); 
            }
            configurarCampos(false);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "No se encontró al empleado.");
        }
    }//GEN-LAST:event_bVerActionPerformed

    private void bEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarActionPerformed
        // TODO add your handling code here:
        String dniEliminar = jtEliminarDNI.getText();

        if (dniEliminar.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el DNI del empleado a eliminar en el recuadro.");
            return;
        }

        Empleado e = SistemaClinico.gestionEmpleados.buscarPorDni(dniEliminar);

        if (e != null) {
            int confirm = JOptionPane.showConfirmDialog(this, 
                    "¿Está seguro de eliminar a " + e.getNombre() + " " + e.getApellido() + "?",
                    "Confirmar Eliminación", JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {
                SistemaClinico.gestionEmpleados.eliminarEmpleado(dniEliminar);

                JOptionPane.showMessageDialog(this, "Empleado eliminado correctamente.");
                cargarTablaEmpleados();
                jtEliminarDNI.setText("");
                limpiarCampos();
            }
        } else {
            JOptionPane.showMessageDialog(this, "ERROR: No se encontró un empleado con ese DNI.");
        }
    }//GEN-LAST:event_bEliminarActionPerformed

    private void bModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificarActionPerformed
        // TODO add your handling code here:
        if (bModificar.getText().equals("Modificar")) {
            int filaSeleccionada = jtEmpleados.getSelectedRow();
            if (filaSeleccionada == -1) {
                JOptionPane.showMessageDialog(this, "Seleccione un empleado de la tabla para modificar.");
                return;
            }

            String dni = jtEmpleados.getValueAt(filaSeleccionada, 0).toString();

            Empleado e = SistemaClinico.gestionEmpleados.buscarPorDni(dni);

            if (e != null) {
                jtDNI.setText(e.getDni());
                jtNombres.setText(e.getNombre());
                jtApellidos.setText(e.getApellido());
                jtTelefono.setText(e.getTelefono());
                jtEmail.setText(e.getEmail());
                jtUsuario.setText(e.getUsuario());
                jtPassword.setText(e.getPassword());
                jcbRol.setSelectedItem(e.getRol());

                if (e instanceof Medico) {
                    jcbEspecialidad.setEnabled(true);
                    jcbEspecialidad.setSelectedItem(((Medico) e).getEspecialidad());
                } else {
                    jcbEspecialidad.setEnabled(false);
                }

                configurarCampos(true); 
                jtDNI.setEnabled(false);

                bModificar.setText("Guardar Cambios");
                bAgregar.setEnabled(false);
                bEliminar.setEnabled(false);
                bVer.setEnabled(false);
            }

        } else {

            String dni = jtDNI.getText();
            Empleado e = SistemaClinico.gestionEmpleados.buscarPorDni(dni);

            if (e != null) {
                String nuevoTelefono = jtTelefono.getText();
                String nuevoEmail = jtEmail.getText();
                String mensaje = SistemaClinico.gestionEmpleados.modificarEmpleado(dni, nuevoTelefono, nuevoEmail);

                e.setNombre(jtNombres.getText());
                e.setApellido(jtApellidos.getText());
                e.setUsuario(jtUsuario.getText());
                e.setPassword(jtPassword.getText());
                e.setRol((String) jcbRol.getSelectedItem());

                if (e instanceof Medico && "Médico".equals(jcbRol.getSelectedItem())) {
                     ((Medico) e).setEspecialidad((String) jcbEspecialidad.getSelectedItem());
                }

                JOptionPane.showMessageDialog(this, "Datos actualizados correctamente.");

                cargarTablaEmpleados();
                limpiarCampos();

                bModificar.setText("Modificar");
                bAgregar.setEnabled(true);
                bEliminar.setEnabled(true);
                bVer.setEnabled(true);

            } else {
                JOptionPane.showMessageDialog(this, "Error: No se encontró el empleado original.");
            }
        }
    }//GEN-LAST:event_bModificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAgregar;
    private javax.swing.JButton bEliminar;
    private javax.swing.JButton bModificar;
    private javax.swing.JButton bVer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jcbEspecialidad;
    private javax.swing.JComboBox<String> jcbRol;
    private javax.swing.JLabel jlDNI;
    private javax.swing.JTextField jtApellidos;
    private javax.swing.JTable jtConsultorios;
    private javax.swing.JTextField jtDNI;
    private javax.swing.JTextField jtEliminarDNI;
    private javax.swing.JTextField jtEmail;
    private javax.swing.JTable jtEmpleados;
    private javax.swing.JTextField jtNombres;
    private javax.swing.JTextField jtPassword;
    private javax.swing.JTextField jtTelefono;
    private javax.swing.JTextField jtUsuario;
    // End of variables declaration//GEN-END:variables
}
