/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Model.Usuario;

/**
 *
 * @author santiago
 */
public class MenuDeOpciones extends javax.swing.JFrame {

    /**
     * Creates new form MenuDeOpciones
     */
    public MenuDeOpciones(Usuario user) {
        initComponents();
        
        switch (user.getRole()){
            case "Administrador":
                this.miConsultas.setEnabled(true);
                this.miPacientes.setEnabled(true);
                this.miEmpleados.setEnabled(true);
                this.miConsultorios.setEnabled(true);
                this.miCitas.setEnabled(true);
                this.miFacturacion.setEnabled(true);
                break;
            case "Médico":
                this.miConsultas.setEnabled(true);
                this.miPacientes.setEnabled(false);
                this.miEmpleados.setEnabled(false);
                this.miConsultorios.setEnabled(true);
                this.miCitas.setEnabled(true);
                this.miFacturacion.setEnabled(true);
                break;
            case "Enfermera":
                this.miConsultas.setEnabled(false);
                this.miPacientes.setEnabled(true);
                this.miEmpleados.setEnabled(false);
                this.miConsultorios.setEnabled(true);
                this.miCitas.setEnabled(true);
                this.miFacturacion.setEnabled(true);
                break;
            case "Cajero":
                this.miConsultas.setEnabled(false);
                this.miPacientes.setEnabled(false);
                this.miEmpleados.setEnabled(false);
                this.miConsultorios.setEnabled(false);
                this.miCitas.setEnabled(false);
                this.miFacturacion.setEnabled(true);
                break;
            case "Recepcionista":
                this.miConsultas.setEnabled(false);
                this.miPacientes.setEnabled(false);
                this.miEmpleados.setEnabled(false);
                this.miConsultorios.setEnabled(false);
                this.miCitas.setEnabled(true);
                this.miFacturacion.setEnabled(true);
                break;
        }
    }
    
    private void mostrarPanel(javax.swing.JPanel nuevoPanel) {
        nuevoPanel.setSize(jpContenidoPrincipal.getWidth(), jpContenidoPrincipal.getHeight());
        nuevoPanel.setLocation(0, 0);
        
        jpContenidoPrincipal.removeAll();
        
        jpContenidoPrincipal.add(nuevoPanel);
        
        jpContenidoPrincipal.revalidate();
        jpContenidoPrincipal.repaint();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jpContenidoPrincipal = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miEmpleados = new javax.swing.JMenuItem();
        miConsultorios = new javax.swing.JMenuItem();
        miPacientes = new javax.swing.JMenuItem();
        miConsultas = new javax.swing.JMenuItem();
        miCitas = new javax.swing.JMenuItem();
        miFacturacion = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenuItem3.setText("jMenuItem3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpContenidoPrincipalLayout = new javax.swing.GroupLayout(jpContenidoPrincipal);
        jpContenidoPrincipal.setLayout(jpContenidoPrincipalLayout);
        jpContenidoPrincipalLayout.setHorizontalGroup(
            jpContenidoPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        jpContenidoPrincipalLayout.setVerticalGroup(
            jpContenidoPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 499, Short.MAX_VALUE)
        );

        jMenu1.setText("Menu");

        miEmpleados.setText("Empleados");
        miEmpleados.setEnabled(false);
        miEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEmpleadosActionPerformed(evt);
            }
        });
        jMenu1.add(miEmpleados);

        miConsultorios.setText("Consultorios");
        miConsultorios.setEnabled(false);
        miConsultorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConsultoriosActionPerformed(evt);
            }
        });
        jMenu1.add(miConsultorios);

        miPacientes.setText("Pacientes");
        miPacientes.setEnabled(false);
        miPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPacientesActionPerformed(evt);
            }
        });
        jMenu1.add(miPacientes);

        miConsultas.setText("Consultas");
        miConsultas.setEnabled(false);
        jMenu1.add(miConsultas);

        miCitas.setText("Citas");
        miCitas.setEnabled(false);
        miCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCitasActionPerformed(evt);
            }
        });
        jMenu1.add(miCitas);

        miFacturacion.setText("Facturacion");
        miFacturacion.setEnabled(false);
        miFacturacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miFacturacionActionPerformed(evt);
            }
        });
        jMenu1.add(miFacturacion);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpContenidoPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpContenidoPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEmpleadosActionPerformed
        // TODO add your handling code here:
        gestorEmpleadoPanel panelEmpleados = new gestorEmpleadoPanel();
        mostrarPanel(panelEmpleados);
    }//GEN-LAST:event_miEmpleadosActionPerformed

    private void miConsultoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultoriosActionPerformed
        // TODO add your handling code here:
        gestorConsultorioPanel panelConsultorios = new gestorConsultorioPanel();
        
        mostrarPanel(panelConsultorios);
    }//GEN-LAST:event_miConsultoriosActionPerformed

    private void miPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPacientesActionPerformed
        // TODO add your handling code here:
        gestorPacientePanel panelPacientes = new gestorPacientePanel();
        mostrarPanel(panelPacientes);
    }//GEN-LAST:event_miPacientesActionPerformed

    private void miCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCitasActionPerformed
        // TODO add your handling code here:
        gestorCitaPanel panelCitas = new gestorCitaPanel();
        mostrarPanel(panelCitas);
    }//GEN-LAST:event_miCitasActionPerformed

    private void miFacturacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miFacturacionActionPerformed
        // TODO add your handling code here:
        gestorFacturaPanel panelFactura = new gestorFacturaPanel();
        mostrarPanel(panelFactura);
    }//GEN-LAST:event_miFacturacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuDeOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuDeOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuDeOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuDeOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuDeOpciones(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jpContenidoPrincipal;
    private javax.swing.JMenuItem miCitas;
    private javax.swing.JMenuItem miConsultas;
    private javax.swing.JMenuItem miConsultorios;
    private javax.swing.JMenuItem miEmpleados;
    private javax.swing.JMenuItem miFacturacion;
    private javax.swing.JMenuItem miPacientes;
    // End of variables declaration//GEN-END:variables
}
